Update chocolatine.yaml

diff --git a/.github/workflows/chocolatine.yaml b/.github/workflows/chocolatine.yaml
--- a/.github/workflows/chocolatine.yaml
+++ b/.github/workflows/chocolatine.yaml
@@ -22,7 +22,24 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Check Repo with banana
-        run: banana-check-repo .
+        run: |
+          set +e
+          banana-check-repo . > errors.txt
+          set -e
+
+          grep "\[Banana\]" errors.txt > banana_errors.txt
+          while IFS= read -r line; do
+            file=$(echo "$line" | cut -d':' -f1)
+            message=$(echo "$line" | sed 's/.*] //' | sed 's/ (C-[A-Z0-9]*)//')
+            type=$(echo "$line" | grep -o "\[Fatal\]\|\[Minor\]\|\[Major\]\|\[Info\]" | tr -d '[]')
+            code=$(echo "$line" | grep -o "C-[A-Z0-9]*")
+            echo "::error file=$file,title=$type coding style error::$code - $message"
+          done < banana_errors.txt
+
+          if grep "\[Banana\]" errors.txt; then
+            exit 1
+          fi
+
 
       - name: Compile
         run: |
@@ -36,10 +53,11 @@ jobs:
             file=$(echo "$line" | cut -d':' -f1)
             line_num=$(echo "$line" | cut -d':' -f2)
             message=$(echo "$line" | sed 's/.*] //' | sed 's/ (C-[A-Z0-9]*)//')
-            type=$(echo "$line" | grep -o "\[Minor\]\|\[Major\]\|\[Info\]" | tr -d '[]')
+            type=$(echo "$line" | grep -o "\[Fatal\]\|\[Minor\]\|\[Major\]\|\[Info\]" | tr -d '[]')
             code=$(echo "$line" | grep -o "C-[A-Z0-9]*")
             echo "::error file=$file,line=$line_num,title=$type coding style error::$code - $message"
           done < banana_errors.txt
+
           if grep "\[Banana\]" errors.txt; then
             exit 1
           fi
